---
title: Collaborating
teaching: 0
exercises: 0
questions:
- "How can I use Rmarkdown to collaborate?"
- "How do I deal with making changes?"
objectives:
- ""
keypoints:
- ""
source: Rmd
---

```{r chunk_options, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("05-")
```

Collaborating w/ Rmd
	If colleagues are comfortable w/ text. Git & Rmd v easy
	
	Of course, very few people are in an environment where that is possible.

	Progress L -> R easy, but changes in Word? 
		One approach: 	use your output as an intermediate product that gets assimilated into bigger file
				Keeps some benefits of Rmd in integrating text & code & outputs
				Loses full reproducibility
				Someone needs to be responsible for integrating and feedback on changes

		Alt?		Produce whole doc in Rmd. Discuss options w/ team for integrating feedback 
				(eg. PI who likes handwritten changes -- great!)
				Or commit to looking at tracked change file and making edits to your Rmd 

		New?		redoc
				(Ex.) Knit to a redoc format. Make some changes in word, then reimport into Rmd and assess.



**integrating python?**
Maybe as a quick demo? 
